### PR TITLE
feat(Server): Added support for variable length requests

### PR DESCRIPTION
**Pull request by gmbeard**
Requests are now read from a `Vec<u8>` buffer and will allow reading
a request object beyond 512 bytes. The parser still uses a fixed header
buffer but I've increased its length to 32. Fixes issue #19

To briefly explain:
This works by marking this indices of the parsed elements within a request, and then "stealing" the underlying buffer. This gets round the borrow checker issues when trying to resize the buffer after using the `httparse::Request::parse` function. I stole the idea from the *hyper* crate.

### CODE REVIEW

**Comment by gmbeard** [comment]
Argh! Please hold off on merging this. I think I’ve introduced a bug by using `io::copy` to read the request stream. I’ll confirm and fix if necessary as soon as I get chance

**Comment by gmbeard** [comment]
Latest commit fixes the previous commit's bug

**Review by steveklabnik — COMMENTED** [review]
Thanks for this! We'll try to review sometime soon.

**Comment by steveklabnik** [comment]
This PR will be merged as part of https://github.com/steveklabnik/simple-server/pull/104. Thanks so much, and sorry the review took so long!

**Pull request closed without merging**
