### PR TITLE
Configurable thread pool size

### LINKED ISSUE #27: make number of Pools configurable
currently hardcoded at 4. https://github.com/steveklabnik/simple-server/blob/4f6050ad6b45caea93ff3caf31eaabfcd75174c3/src/lib.rs#L84

not urgent but nice to have

### PR DESCRIPTION
**Pull request by gsquire**
Fixes #27 

I'm not sure if this is desired so if it isn't, feel free to close it.

### CODE REVIEW

**Comment by ashleygwilliams** [comment]
hey @gsquire ! thanks so much for this. this makes the default value way more intelligent. it turns out that the original spirit of my extremely not detailed issue ( #27 ) was that we would also accept an env variable that would designate the number.

if you are interested in adding that to this PR we would love it! otherwise we'll accept this and do the env variable work in another PR. just lemme know! thanks for the contribution!

**Comment by gsquire** [comment]
I can certainly add that. Here is how I envision the flow:

If the environment variable is present (let me know what name sounds good), try and parse it as a `u32`. If this fails or the variable isn't present, then I will default to the number of CPUs. How does that sound?

**Comment by ashleygwilliams** [comment]
hey @gsquire ! that sounds absolutely perfect. thank you so much!!

**Comment by ashleygwilliams** [comment]
cc i dont know if  @steveklabnik has a pref

**Comment by gsquire** [comment]
I can update that soon and then change it if need be based on his response :)

**Comment by steveklabnik** [comment]
Rust's testing framework uses `RUST_TEST_THREADS` to set the number of threads, what about `SIMPLESERVER_THREADS`?

Env vars don't have namespacing, so you kind of have to do it in the name...

**Comment by gsquire** [comment]
Ok I adjusted it to `SIMPLESERVER_THREADS`. Let me know if you would like me to squash my commits.

**Comment by ashleygwilliams** [comment]
this looks great @gsquire ! if you wanna fix up that last commit into the main commit you've got i think we can ship this! thank u so much for your patience, flexibility, and work ✨ ❤️

**Comment by gsquire** [comment]
No problem, happy to contribute. Should be all set now.

**Pull request merged**
